{% set name = "dlatk" %}
{% set version = "1.2.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dlatk-{{ version }}.tar.gz
  sha256: 8f7d51eb19a65d727d359520d855e1b3dc03675bd0f395f86ddb5bc97546ab4e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - numpy
  run:
    - mysqlclient
    - nltk >=3.2.1
    - numpy
    - pandas >=0.20.3
    - patsy >=0.2.1
    - python >=3.6
    - python-dateutil >=2.5.0
    - scikit-learn <0.24.0
    - scipy >=0.13.3
    - sqlalchemy >=0.9.9
    - statsmodels >=0.5.0

test:
  imports:
    - dlatk
    - dlatk.lexicainterface
  requires:
    - pip
  commands:
    - pip check
    - dlatkInterface.py -h

about:
  home: http://dlatk.wwbp.org
  summary: End to end human text analysis package.
  description: |
    DLATK is an end to end human text analysis package, specifically
    suited for social media and social scientific applications. It is written in 
    Python 3 and developed by the World Well-Being Project at the University of 
    Pennsylvania and Stony Brook University.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - izahn
    - sjgiorgi
